#!/usr/bin/env python3

import argparse
import difflib
import json
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List, Sequence, Tuple


REPO_ROOT = Path(__file__).resolve().parent.parent
RUNTIME_ROOT = REPO_ROOT / "runtime"
GENERATED_ROOT = RUNTIME_ROOT / "generated"
CATALOG_ROOT = RUNTIME_ROOT / "catalog"

KIND_TO_FILENAME = {
    "agent-entry": "agent-entry.md",
    "troubleshooting-entry": "troubleshooting-entry.md",
    "retrieval-order": "retrieval-order.md",
    "skill-bridge": "skill-bridge.md",
}

KIND_ORDER = tuple(KIND_TO_FILENAME)
CANONICAL_INPUTS = (
    RUNTIME_ROOT / "contract.json",
    RUNTIME_ROOT / "surface.json",
    CATALOG_ROOT / "scenarios.json",
    CATALOG_ROOT / "playbooks.json",
    CATALOG_ROOT / "nodes.json",
    CATALOG_ROOT / "prompts.json",
    CATALOG_ROOT / "sources.json",
)
GENERATED_BANNER = (
    "<!-- Generated by scripts/render_runtime_views.py from "
    "runtime/contract.json, runtime/surface.json, and runtime/catalog/*.json. -->"
)


class RenderError(Exception):
    pass


def normalize_path(value: str) -> str:
    return value.replace("\\", "/")


def repo_relative(path: Path) -> str:
    return normalize_path(str(path.relative_to(REPO_ROOT)))


def load_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise RenderError(f"missing runtime input: {repo_relative(path)}") from exc
    except json.JSONDecodeError as exc:
        raise RenderError(
            f"invalid JSON in {repo_relative(path)} at line {exc.lineno}, column {exc.colno}: {exc.msg}"
        ) from exc


def require_object(value: Any, label: str) -> Dict[str, Any]:
    if not isinstance(value, dict):
        raise RenderError(f"{label} must be a JSON object")
    return value


def require_list(value: Any, label: str) -> List[Any]:
    if not isinstance(value, list):
        raise RenderError(f"{label} must be a JSON array")
    return value


def require_string(value: Any, label: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise RenderError(f"{label} must be a non-empty string")
    return value


def require_string_list(value: Any, label: str) -> List[str]:
    items = require_list(value, label)
    result: List[str] = []
    for index, item in enumerate(items):
        result.append(require_string(item, f"{label}[{index}]").strip())
    return result


def load_catalog(name: str) -> Dict[str, Any]:
    payload = require_object(
        load_json(CATALOG_ROOT / f"{name}.json"), f"catalog:{name}"
    )
    items = require_list(payload.get("items"), f"catalog:{name}.items")
    for index, item in enumerate(items):
        entry = require_object(item, f"catalog:{name}.items[{index}]")
        require_string(entry.get("id"), f"catalog:{name}.items[{index}].id")
        require_string(entry.get("path"), f"catalog:{name}.items[{index}].path")
        require_string(entry.get("status"), f"catalog:{name}.items[{index}].status")
        require_string_list(
            entry.get("aliases", []), f"catalog:{name}.items[{index}].aliases"
        )
    return payload


def active_items(catalog: Dict[str, Any]) -> List[Dict[str, Any]]:
    items = require_list(catalog.get("items"), "catalog.items")
    active: List[Dict[str, Any]] = []
    for item in items:
        entry = require_object(item, "catalog.items[]")
        if entry.get("status") == "active":
            active.append(entry)
    return active


def item_by_id(catalog: Dict[str, Any], item_id: str) -> Dict[str, Any]:
    for item in active_items(catalog):
        if item.get("id") == item_id:
            return item
    raise RenderError(f"missing active catalog item '{item_id}'")


def format_alias_suffix(item: Dict[str, Any]) -> str:
    aliases = [
        alias for alias in item.get("aliases", []) if isinstance(alias, str) and alias
    ]
    if not aliases:
        return ""
    quoted = ", ".join(f"`{alias}`" for alias in aliases)
    return f" (aliases: {quoted})"


def format_catalog_line(item: Dict[str, Any]) -> str:
    return f"- `{item['id']}` -> `{item['path']}`{format_alias_suffix(item)}"


def format_path_lines(paths: Iterable[str]) -> List[str]:
    return [f"- `{path}`" for path in paths]


def format_indented_path_lines(paths: Iterable[str]) -> List[str]:
    return [f"   - `{path}`" for path in paths]


def format_indented_plain_lines(items: Iterable[str]) -> List[str]:
    return [f"   - {item}" for item in items]


def render_markdown_list(items: Sequence[str]) -> List[str]:
    return [f"{index}. {item}" for index, item in enumerate(items, start=1)]


def first_present(paths: Sequence[str], target: str) -> bool:
    return any(path == target for path in paths)


def build_runtime_state() -> Dict[str, Any]:
    contract = require_object(load_json(RUNTIME_ROOT / "contract.json"), "contract")
    surface = require_object(load_json(RUNTIME_ROOT / "surface.json"), "surface")
    scenarios = load_catalog("scenarios")
    playbooks = load_catalog("playbooks")
    nodes = load_catalog("nodes")
    prompts = load_catalog("prompts")
    sources = load_catalog("sources")

    contract_entrypoints = require_string_list(
        contract.get("runtime_entrypoints"), "contract.runtime_entrypoints"
    )
    optional_helpers = require_string_list(
        contract.get("optional_helpers"), "contract.optional_helpers"
    )
    fallback_behavior = require_object(
        contract.get("fallback_behavior"), "contract.fallback_behavior"
    )
    manual_inputs = require_string_list(
        fallback_behavior.get("minimum_manual_inputs"),
        "contract.fallback_behavior.minimum_manual_inputs",
    )
    helper_fallback = require_string_list(
        fallback_behavior.get("when_optional_helpers_are_unavailable"),
        "contract.fallback_behavior.when_optional_helpers_are_unavailable",
    )
    surface_policy = require_object(
        contract.get("runtime_surface_policy"), "contract.runtime_surface_policy"
    )
    default_runtime_dependencies = require_string_list(
        surface_policy.get("default_runtime_dependencies"),
        "contract.runtime_surface_policy.default_runtime_dependencies",
    )
    default_retrieval_policy = require_object(
        surface.get("default_retrieval_policy"), "surface.default_retrieval_policy"
    )
    entry_surfaces = require_string_list(
        default_retrieval_policy.get("entry_surfaces"),
        "surface.default_retrieval_policy.entry_surfaces",
    )
    include_runtime_support_when = require_string_list(
        default_retrieval_policy.get("include_runtime_support_when"),
        "surface.default_retrieval_policy.include_runtime_support_when",
    )
    exclude_by_default = require_string_list(
        default_retrieval_policy.get("exclude_by_default"),
        "surface.default_retrieval_policy.exclude_by_default",
    )

    active_scenarios = active_items(scenarios)
    active_playbooks = active_items(playbooks)
    active_nodes = active_items(nodes)
    active_prompts = active_items(prompts)
    active_sources = active_items(sources)

    routing_playbooks = [
        item
        for item in active_playbooks
        if "/debug-routing/" in str(item.get("path", ""))
    ]
    operational_playbooks = [
        item
        for item in active_playbooks
        if "/debug-routing/" not in str(item.get("path", ""))
    ]

    prompt_map = {item["id"]: item for item in active_prompts}
    generated_paths = {
        kind: repo_relative(GENERATED_ROOT / filename)
        for kind, filename in KIND_TO_FILENAME.items()
    }

    return {
        "contract": contract,
        "surface": surface,
        "contract_entrypoints": contract_entrypoints,
        "optional_helpers": optional_helpers,
        "manual_inputs": manual_inputs,
        "helper_fallback": helper_fallback,
        "default_runtime_dependencies": default_runtime_dependencies,
        "entry_surfaces": entry_surfaces,
        "include_runtime_support_when": include_runtime_support_when,
        "exclude_by_default": exclude_by_default,
        "scenarios": active_scenarios,
        "playbooks": active_playbooks,
        "routing_playbooks": routing_playbooks,
        "operational_playbooks": operational_playbooks,
        "nodes": active_nodes,
        "prompts": active_prompts,
        "prompt_map": prompt_map,
        "sources": active_sources,
        "sources_catalog": sources,
        "generated_paths": generated_paths,
        "parallel_triage_available": first_present(
            require_string_list(
                surface.get("runtime_public"), "surface.runtime_public"
            ),
            "PARALLEL_TRIAGE_DECISION_TREE.md",
        ),
        "setup_playbook": item_by_id(playbooks, "first-pass-case-setup-checklist"),
        "setup_prompt": prompt_map.get("setup-assistant"),
        "troubleshooting_prompt": prompt_map.get("troubleshooting-assistant"),
        "review_prompt": prompt_map.get("case-review"),
        "source_prompt": prompt_map.get("source-triage-assistant"),
    }


def render_agent_entry(state: Dict[str, Any]) -> str:
    lines = [
        GENERATED_BANNER,
        "# Runtime Agent Entry",
        "",
        "Use this read-only summary for quick entry. Canonical runtime metadata under `runtime/` remains the source of truth.",
        "",
        "## Runtime spine",
        f"- Consumer model: `{state['contract']['consumer_model']}`",
        f"- Generated views live under `{repo_relative(GENERATED_ROOT)}/` and are safe to regenerate.",
        "Current contract entrypoints:",
    ]
    lines.extend(format_path_lines(state["contract_entrypoints"]))
    lines.extend(
        [
            "",
            "## Default retrieval boundary",
            "- Read `runtime_public` first.",
        ]
    )
    lines.extend(f"- {item}" for item in state["include_runtime_support_when"])
    lines.append(
        "- Excluded by default: "
        + ", ".join(f"`{item}`" for item in state["exclude_by_default"])
    )
    lines.extend(
        [
            "",
            "## Task lanes",
            "### Case setup",
            "1. Open `AGENT_ENTRY.md` or this generated view.",
            "2. Match the case to the closest scenario template from the canonical scenario catalog.",
            f"3. Start with `{state['setup_playbook']['id']}` at `{state['setup_playbook']['path']}`.",
        ]
    )
    if state["setup_prompt"] is not None:
        lines.append(
            f"4. Use prompt `{state['setup_prompt']['id']}` at `{state['setup_prompt']['path']}` for answer shaping."
        )
    else:
        lines.append("4. Use the setup prompt from `prompts/` for answer shaping.")
    lines.extend(
        [
            "",
            "### Troubleshooting",
            "1. If a local case path is available and Python is available, run the optional helper first.",
        ]
    )
    lines.extend(format_indented_path_lines(state["optional_helpers"]))
    lines.extend(
        [
            "2. If the helper cannot run, collect the minimum manual inputs and continue with the authored entry surfaces.",
            "3. Open `TROUBLESHOOTING_ENTRY.md`, match the scenario, then use the routing playbooks before loading troubleshooting nodes.",
        ]
    )
    if state["troubleshooting_prompt"] is not None:
        lines.append(
            f"4. Use prompt `{state['troubleshooting_prompt']['id']}` at `{state['troubleshooting_prompt']['path']}`."
        )
    lines.extend(
        [
            "",
            "### Case review",
            "1. Match the scenario template first.",
        ]
    )
    if state["review_prompt"] is not None:
        lines.append(
            f"2. Use prompt `{state['review_prompt']['id']}` at `{state['review_prompt']['path']}`."
        )
    lines.append(
        f"3. Reuse `{state['setup_playbook']['id']}` before opening troubleshooting nodes."
    )
    if state["source_prompt"] is not None:
        lines.extend(
            [
                "",
                "### Source triage",
                f"1. Use prompt `{state['source_prompt']['id']}` at `{state['source_prompt']['path']}`.",
                "2. Treat `runtime/catalog/sources.json` as the canonical source registry summary and `references/source-index.yaml` as the backing registry file.",
            ]
        )

    lines.extend(
        [
            "",
            "## Active routing structure",
            f"- Scenario templates: {len(state['scenarios'])}",
        ]
    )
    lines.extend(format_catalog_line(item) for item in state["scenarios"])
    lines.append(f"- Operational playbooks: {len(state['operational_playbooks'])}")
    lines.extend(format_catalog_line(item) for item in state["operational_playbooks"])
    lines.append(f"- Routing playbooks: {len(state['routing_playbooks'])}")
    lines.extend(format_catalog_line(item) for item in state["routing_playbooks"])
    lines.extend(
        [
            f"- Troubleshooting node pool: {len(state['nodes'])} active nodes under `ontology/troubleshooting-graph/nodes/`.",
            "",
            "## Default authored runtime collections",
        ]
    )
    lines.extend(
        format_path_lines(
            path for path in state["default_runtime_dependencies"] if path.endswith("/")
        )
    )
    return "\n".join(lines) + "\n"


def render_troubleshooting_entry(state: Dict[str, Any]) -> str:
    lines = [
        GENERATED_BANNER,
        "# Runtime Troubleshooting Entry",
        "",
        "Use this read-only troubleshooting map as a generated summary. Canonical runtime metadata under `runtime/` remains the source of truth.",
        "",
        "## Ordered troubleshooting path",
        "1. If a local case path is available and Python is available, run the optional helper first.",
    ]
    lines.extend(format_indented_path_lines(state["optional_helpers"]))
    lines.extend(
        [
            "2. If the helper is unavailable, collect the minimum manual inputs:",
        ]
    )
    lines.extend(format_indented_plain_lines(state["manual_inputs"]))
    lines.append("3. Continue with the authored runtime entry surfaces:")
    lines.extend(
        format_indented_path_lines(
            [
                "CASE_AUTO_INTAKE_SPEC.md",
                "CASE_TRIAGE_PLAYBOOK.md",
                "TROUBLESHOOTING_ENTRY.md",
            ]
        )
    )
    lines.append("4. Match the case to the closest canonical scenario template.")
    lines.append("5. Use the routing playbooks in this order:")
    lines.extend(
        f"   - `{item['id']}` -> `{item['path']}`{format_alias_suffix(item)}"
        for item in state["routing_playbooks"]
    )
    if state["parallel_triage_available"]:
        lines.append(
            "   - `PARALLEL_TRIAGE_DECISION_TREE.md` for parallel-sensitive branches"
        )
    lines.extend(
        [
            "6. Open the most relevant operational playbook and then load the top matching troubleshooting nodes.",
        ]
    )
    if state["troubleshooting_prompt"] is not None:
        lines.append(
            f"7. Use prompt `{state['troubleshooting_prompt']['id']}` at `{state['troubleshooting_prompt']['path']}` to keep the answer ordered."
        )

    lines.extend(
        [
            "",
            "## Canonical scenario families",
        ]
    )
    lines.extend(format_catalog_line(item) for item in state["scenarios"])
    lines.extend(
        [
            "",
            "## Operational playbooks available after routing",
        ]
    )
    lines.extend(format_catalog_line(item) for item in state["operational_playbooks"])
    lines.extend(
        [
            "",
            "## Runtime support surfaces for troubleshooting",
            "- `runtime/contract.json` for helper and fallback policy",
            "- `runtime/surface.json` for retrieval boundary rules",
            "- `runtime/catalog/scenarios.json`, `runtime/catalog/playbooks.json`, and `runtime/catalog/nodes.json` for canonical IDs and paths",
            f"- Troubleshooting node pool: {len(state['nodes'])} active nodes under `ontology/troubleshooting-graph/nodes/`",
        ]
    )
    return "\n".join(lines) + "\n"


def render_retrieval_order(state: Dict[str, Any]) -> str:
    lines = [
        GENERATED_BANNER,
        "# Runtime Retrieval Order",
        "",
        "Use this file to keep retrieval deterministic. Canonical runtime metadata under `runtime/` remains the source of truth.",
        "",
        "## Default surface policy",
        "- Start with `runtime_public`.",
    ]
    lines.extend(f"- {item}" for item in state["include_runtime_support_when"])
    lines.append(
        "- Exclude by default: "
        + ", ".join(f"`{item}`" for item in state["exclude_by_default"])
    )
    lines.extend(
        [
            "",
            "## Case setup tasks",
            "1. Open `AGENT_ENTRY.md`.",
            "2. Match the closest canonical scenario template.",
            f"3. Start with `{state['setup_playbook']['path']}`.",
        ]
    )
    if state["setup_prompt"] is not None:
        lines.append(f"4. Use `{state['setup_prompt']['path']}` for response framing.")
    lines.append(
        "5. Pull only the authored runtime collections you need from the default runtime dependencies."
    )
    lines.extend(
        [
            "",
            "## Troubleshooting tasks",
            "1. If a local case path exists, run the optional helper first.",
        ]
    )
    lines.extend(format_indented_path_lines(state["optional_helpers"]))
    lines.extend(
        [
            "2. If helper execution is unavailable, use `CASE_AUTO_INTAKE_SPEC.md` and `CASE_TRIAGE_PLAYBOOK.md`.",
            "3. Open `TROUBLESHOOTING_ENTRY.md`.",
            "4. Match the closest canonical scenario template.",
            "5. Read the routing playbooks before choosing an operational playbook.",
            "6. Load only the top matching troubleshooting nodes, then widen into authored knowledge if needed.",
        ]
    )
    if state["troubleshooting_prompt"] is not None:
        lines.append(
            f"7. Use `{state['troubleshooting_prompt']['path']}` for ordered output."
        )
    lines.extend(
        [
            "",
            "## Case-review tasks",
            "1. Match the scenario template first.",
        ]
    )
    if state["review_prompt"] is not None:
        lines.append(f"2. Use `{state['review_prompt']['path']}`.")
    lines.extend(
        [
            f"3. Reuse `{state['setup_playbook']['path']}` before widening into troubleshooting nodes.",
            "4. Load troubleshooting nodes only for concrete red-flag branches.",
        ]
    )
    if state["source_prompt"] is not None:
        lines.extend(
            [
                "",
                "## Source-triage and runtime-maintenance tasks",
                f"1. Use `{state['source_prompt']['path']}`.",
                "2. Read `runtime/catalog/sources.json` first for canonical source IDs and registry pointers.",
                "3. Use `references/source-index.yaml` and `references/citation-map.yaml` only as runtime-support artifacts, not as default entry surfaces.",
            ]
        )
    return "\n".join(lines) + "\n"


def render_skill_bridge(state: Dict[str, Any]) -> str:
    lines = [
        GENERATED_BANNER,
        "# Runtime Skill Bridge",
        "",
        "Use this generated bridge note when another agent or skill needs a stable entry contract for this repository. Canonical runtime metadata under `runtime/` remains the source of truth.",
        "",
        "## Preflight",
        "1. Verify the repository root exists on the local machine.",
        "2. Verify these runtime entrypoints exist under that root:",
    ]
    lines.extend(format_indented_path_lines(state["contract_entrypoints"]))
    lines.extend(
        [
            "3. Treat generated runtime views as convenience surfaces, not as the only truth source:",
        ]
    )
    lines.extend(format_indented_path_lines(state["generated_paths"].values()))
    lines.extend(
        [
            "",
            "## Bridge responsibility",
            "Use the bridge only to locate the repository, verify the runtime surface, and hand the task off to the correct authored or generated entry document.",
            "",
            "## Task handoff",
            "- Setup or case review: open `runtime/generated/agent-entry.md`, then continue with `AGENT_ENTRY.md` if the authored wrapper is needed.",
            "- Troubleshooting: open `runtime/generated/troubleshooting-entry.md`, then continue with `TROUBLESHOOTING_ENTRY.md` if classifier guidance is needed.",
            "- Retrieval order: use `runtime/generated/retrieval-order.md` as the current generated reading-order summary.",
            "",
            "## Boundary rules",
            "- Use `runtime/contract.json` for helper and fallback policy.",
            "- Use `runtime/surface.json` for retrieval-boundary rules.",
            "- Keep project-state and validation-history documents outside the default runtime path.",
            "- If a generated view and canonical runtime metadata ever disagree, prefer the canonical runtime metadata.",
            "- The bridge is navigation, not diagnosis.",
        ]
    )
    return "\n".join(lines) + "\n"


def render_view(kind: str, state: Dict[str, Any]) -> str:
    if kind == "agent-entry":
        return render_agent_entry(state)
    if kind == "troubleshooting-entry":
        return render_troubleshooting_entry(state)
    if kind == "retrieval-order":
        return render_retrieval_order(state)
    if kind == "skill-bridge":
        return render_skill_bridge(state)
    raise RenderError(f"unsupported render kind '{kind}'")


def target_path_for_kind(kind: str) -> Path:
    return GENERATED_ROOT / KIND_TO_FILENAME[kind]


def selected_kinds(kind: str) -> List[str]:
    return [kind] if kind else list(KIND_ORDER)


def write_views(state: Dict[str, Any], kind: str) -> int:
    GENERATED_ROOT.mkdir(parents=True, exist_ok=True)
    written = 0
    for target_kind in selected_kinds(kind):
        output_path = target_path_for_kind(target_kind)
        output_path.write_text(render_view(target_kind, state), encoding="utf-8")
        print(f"WROTE [{target_kind}] {repo_relative(output_path)}")
        written += 1
    print(f"Summary: wrote {written} generated runtime view(s).")
    return 0


def diff_preview(expected: str, actual: str) -> List[str]:
    diff_lines = list(
        difflib.unified_diff(
            expected.splitlines(),
            actual.splitlines(),
            fromfile="expected",
            tofile="actual",
            lineterm="",
        )
    )
    if len(diff_lines) > 40:
        diff_lines = diff_lines[:40] + ["... diff truncated ..."]
    return diff_lines


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        raise RenderError(f"missing comparison file: {path}") from exc


def compare_one(kind: str, expected: str, path: Path) -> bool:
    actual = read_text(path)
    if actual == expected:
        try:
            location = repo_relative(path)
        except ValueError:
            location = str(path)
        print(f"PASS [{kind}] {location}")
        return True

    try:
        location = repo_relative(path)
    except ValueError:
        location = str(path)
    print(f"FAIL [{kind}] {location}")
    for line in diff_preview(expected, actual):
        print(f"  {line}")
    return False


def check_views(state: Dict[str, Any], kind: str, compare_file: str) -> int:
    failures = 0
    checked = 0

    if compare_file:
        if not kind:
            raise RenderError("--compare-file requires --kind")
        checked += 1
        if not compare_one(
            kind, render_view(kind, state), Path(compare_file).expanduser()
        ):
            failures += 1
    else:
        for target_kind in selected_kinds(kind):
            checked += 1
            if not compare_one(
                target_kind,
                render_view(target_kind, state),
                target_path_for_kind(target_kind),
            ):
                failures += 1

    print(f"Summary: checked {checked} generated runtime view(s), {failures} drifted.")
    return 1 if failures else 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render and drift-check runtime-generated markdown views."
    )
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument(
        "--write",
        action="store_true",
        help="Write rendered views under runtime/generated/.",
    )
    action.add_argument(
        "--check",
        action="store_true",
        help="Check generated views for drift without writing files.",
    )
    parser.add_argument(
        "--kind",
        choices=sorted(KIND_TO_FILENAME.keys()),
        help="Render or check only one generated view kind.",
    )
    parser.add_argument(
        "--compare-file",
        help="Compare rendered output for --kind against an arbitrary file path.",
    )
    args = parser.parse_args()
    if args.write and args.compare_file:
        parser.error("--compare-file can only be used with --check")
    if args.compare_file and not args.kind:
        parser.error("--compare-file requires --kind")
    return args


def main() -> int:
    args = parse_args()
    state = build_runtime_state()
    if args.write:
        return write_views(state, args.kind)
    return check_views(state, args.kind, args.compare_file)


if __name__ == "__main__":
    try:
        sys.exit(main())
    except RenderError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)
